config/routes.rb
SampleApp::Application.routes.draw do
  get "announcements/new"

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :upload, :as => "data_files"
  resources :registrants
  resources :announcements
      
  root to: 'static_pages#home'

  match '/announcements', to: 'announcements#new'
  match '/register',      to: 'registrants#new'
  match '/signup',        to: 'users#new'
  match '/signin',        to: 'sessions#new'
  match '/signout',       to: 'sessions#destroy'
      
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/directions', to: 'static_pages#directions'
  match '/accommodations', to: 'static_pages#accommodations'
  match '/schedule', to: 'static_pages#schedule'
  match '/call_for_papers', to: 'static_pages#call_for_papers'
  match '/forum', to: 'static_pages#forum'
  match '/uploadfile/index', to: 'upload#index'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.claremontmckenna.edu">Claremont Mckenna Home Page</a>
  </small>
  <nav>
    <ul>
      <%  if signed_in?  %>
         <li><%= link_to "Registrants", registrants_path %></li>
         <li><%= link_to "Submitted Papers", root_url + "upload" %></li>
         <li><%= link_to "Admin Sign Out", root_url + "signout" %></li>
    <% else %>
        <li><%= link_to "Admin Login", signin_path %></li>
      <% end %>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="top-header">
  <div class="title">
    Workshop in Macroeconomics
  </div>
  <div class="title-two">
    at Liberal Arts Colleges 2013
  </div>
  <div class="title-three">
    <a href="http://www.claremontmckenna.edu">Claremont Mckenna College</a>
  </div>
</div>

<div class="top-of-page-two">
     <div class="header-text">
       <div class="spacing">
         <%= link_to "Home", root_path, style: "color: #EBEBEB"%>
       </div>
       <div class="spacing">
         <%= link_to "Accommodations", accommodations_path, style: "color: #EBEBEB" %>
       </div>
       <div class="spacing">
         <%= link_to "Directions", directions_path, style: "color: #EBEBEB" %>
       </div>
       <div class="spacing">
         <%= link_to "Call for Papers", call_for_papers_path, style: "color: #EBEBEB" %>
       </div>
       <div class="spacing">
         <%= link_to "Submit", new_data_file_path, style: "color: #EBEBEB" %>
       </div>
       <div class="spacing">
         <%= link_to "Preregister", new_registrant_path, style: "color: #EBEBEB" %>
       </div>
       <div class="spacing2">
         <%= link_to "Conference Schedule", schedule_path, style: "color: #EBEBEB" %>
       </div>
     </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="bucket">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>